version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=mis
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    container_name: server_mobile
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

volumes:
  postgres:
